FROM balenalib/armv7hf

ARG RASPBIAN_VERSION

env $RASPBIAN_VERSION

RUN [ "cross-build-start" ]

RUN apt-get update && apt-get -y wget unzip

RUN [ "cross-build-end" ]

WORKDIR /var/builder

COPY rpi/tools/* ./

CMD [ "./build-kodi.sh" ]