name: basic_builder
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]


jobs:
  basic_build:
    runs-on: ubuntu-18.04
    name: build_image
    env:
      ECR_REPO: .dkr.ecr.us-east-2.amazonaws.com
      DOCKER_IMAGE: ubuntu.basic
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MASA_AWS_KEY }}
          aws-secret-access-key: ${{ secrets.MASA_AWS_SECRET }}
          aws-region: us-east-2
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build Image
        run: |
          docker build -t $DOCKER_IMAGE -f ubuntu/Dockerfile.basic .
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push to ECR
        env:
          LATEST_IMAGE: $DOCKER_IMAGE:latest
        run: |
          docker tag $DOCKER_IMAGE:latest $${ secrets.MASA_AWS_ACCT_ID }}$ECR_REPO/$DOCKER_IMAGE:latest:$GITHUB_SHA
          docker push $${ secrets.MASA_AWS_ACCT_ID }}$ECR_REPO/$DOCKER_IMAGE:latest:$GITHUB_SHA
