name: basic_builder
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  basic_build:
    runs-on: ubuntu-18.04
    name: build_image
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MASA_AWS_KEY }}
          aws-secret-access-key: ${{ secrets.MASA_AWS_SECRET }}
          aws-region: us-east-2
      - name: Fetch Base Image
        run: |
          aws s3 cp s3://ear-collection/test.txt .
          cat test.txt
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build Image
        run: |
          cd arm && docker build -t gateway_build -f Dockerfile .
      - name: Run Image
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
          docker run --privileged  gateway_build
